const ipoTarget = {
	measure: "public-market-capitalization",
	statistic: "current-equivalent",
	capitalizationBasis: "outstanding-shares",
	currency: "USD",
};

const thresholdTarget = {
	measure: "qualifying-company-valuation",
	statistic: "maximum-by-deadline",
	capitalizationBasis: "provider-defined",
	currency: "USD",
};

function ipoAssumptions(value: {
	discountRate: number;
	expectedDate: string;
	lowerValue: number;
	upperValue: number;
	noIpoCurrentValue: number;
	asOf: string;
	sourceUrl: string;
}) {
	return {
		discountRate: value.discountRate,
		expectedDate: value.expectedDate,
		lowerValue: value.lowerValue,
		upperValue: value.upperValue,
		noIpoCurrentValue: value.noIpoCurrentValue,
		provenance: {
			asOf: value.asOf,
			basis: "analyst-scenario",
			sourceUrl: value.sourceUrl,
			rationale:
				"Scenario inputs translate the source IPO capitalization ladder into current-equivalent dollars. They are not additional market observations.",
		},
		uncertainty: {
			discountRateLow: Math.max(0, value.discountRate - 0.05),
			discountRateHigh: value.discountRate + 0.1,
			noIpoValueLow: value.noIpoCurrentValue * 0.75,
			noIpoValueHigh: value.noIpoCurrentValue * 1.25,
		},
	};
}

function thresholdAssumptions(value: {
	growthRate: number;
	expectedDate: string;
	floorValue: number;
	upperValue: number;
	asOf: string;
	sourceUrl: string;
}) {
	return {
		growthRate: value.growthRate,
		expectedDate: value.expectedDate,
		floorValue: value.floorValue,
		upperValue: value.upperValue,
		provenance: {
			asOf: value.asOf,
			basis: "analyst-scenario",
			sourceUrl: value.sourceUrl,
			rationale:
				"The floor, open tail, and deadline-peak translation rate are explicit scenario inputs rather than prediction-market facts.",
		},
		uncertainty: {
			growthRateLow: 0,
			growthRateHigh: 0.25,
			floorValueLow: value.floorValue * 0.75,
			floorValueHigh: value.floorValue,
			upperValueLow: value.upperValue,
			upperValueHigh: value.upperValue * 1.5,
		},
	};
}

function thresholdClaim(slug: string) {
	return {
		id: `${slug}-npm-price`,
		statistic: "maximum-by-deadline",
		deadline: "2026-12-31",
		comparison: "at-least",
		valuationSource: "npm-price",
		capitalizationBasis: "provider-defined",
		rulesUrl: `https://polymarket.com/event/${slug}`,
		eligibleEvents: ["npm-price", "public-market-capitalization"],
	};
}

function thresholdCompany(value: {
	id: string;
	name: string;
	code: string;
	number: string;
	sector: string;
	event: string;
	floorValue: number;
	upperValue: number;
	thresholds: Array<[string, number]>;
}) {
	const url = `https://polymarket.com/event/${value.event}`;
	return {
		id: value.id,
		slug: value.id,
		name: value.name,
		code: value.code,
		number: value.number,
		sector: value.sector,
		description: `Polymarket provides an NPM Price threshold curve for ${value.name}, measuring the maximum qualifying valuation reached through December 31, 2026.`,
		methods: [
			{
				id: "valuation-high-2026",
				method: "prediction-market-valuation-thresholds",
				family: "prediction-market",
				familyWeight: 1,
				weight: 1,
				target: thresholdTarget,
				storage: "live",
				assumptions: thresholdAssumptions({
					growthRate: 0.1,
					expectedDate: "2026-12-31",
					floorValue: value.floorValue,
					upperValue: value.upperValue,
					asOf: "2026-07-30T00:00:00.000Z",
					sourceUrl: url,
				}),
				data: {
					provider: "polymarket",
					events: [
						{
							id: "main",
							slug: value.event,
							url,
							api: `https://gamma-api.polymarket.com/events/slug/${value.event}`,
						},
					],
					thresholds: value.thresholds.map(([sourceTitle, threshold], i) => ({
						event: "main",
						sourceTitle,
						key: `over-${threshold}`,
						label: `${sourceTitle.slice(1)} or higher`,
						value: threshold,
						sortOrder: i + 1,
					})),
					claim: thresholdClaim(value.event),
				},
			},
		],
	};
}

function ipoMethod(value: {
	id: string;
	weight: number;
	event: string;
	expectedDate: string;
	lowerValue: number;
	upperValue: number;
	noIpoCurrentValue: number;
	asOf: string;
	upperKey: string;
	noIpoTitle: string;
	ranges: Array<{
		sourceTitle: string;
		key: string;
		label: string;
		lower: number | null;
		upper: number | null;
	}>;
}) {
	const url = `https://polymarket.com/event/${value.event}`;
	return {
		id: value.id,
		method: "prediction-market-ipo",
		family: "prediction-market",
		familyWeight: 1,
		weight: value.weight,
		target: ipoTarget,
		storage: "live",
		upperKey: value.upperKey,
		assumptions: ipoAssumptions({
			discountRate: 0.1,
			expectedDate: value.expectedDate,
			lowerValue: value.lowerValue,
			upperValue: value.upperValue,
			noIpoCurrentValue: value.noIpoCurrentValue,
			asOf: value.asOf,
			sourceUrl: url,
		}),
		data: {
			provider: "polymarket",
			events: [
				{
					id: "main",
					slug: value.event,
					url,
					api: `https://gamma-api.polymarket.com/events/slug/${value.event}`,
				},
			],
			outcomes: [
				...value.ranges.map((range, i) => ({
					event: "main",
					...range,
					kind: "range",
					representativeValue:
						range.lower == null
							? value.lowerValue
							: range.upper == null
								? value.upperValue
								: (range.lower + range.upper) / 2,
					sortOrder: i + 1,
				})),
				{
					event: "main",
					sourceTitle: value.noIpoTitle,
					key: "no-ipo",
					label: "No IPO by deadline",
					kind: "no_ipo",
					lower: null,
					upper: null,
					representativeValue: null,
					sortOrder: value.ranges.length + 1,
				},
			],
		},
	};
}

export const companyData = [
	{
		id: "anthropic",
		slug: "anthropic",
		name: "Anthropic",
		code: "ANTHROPIC",
		number: "01",
		sector: "Artificial intelligence",
		description:
			"Polymarket provides two IPO-capitalization ladders for Anthropic plus a maximum qualifying valuation curve by deadline.",
		methods: [
			{
				id: "ipo-closing-2027",
				method: "prediction-market-ipo",
				family: "prediction-market",
				familyWeight: 1,
				weight: 0.5,
				target: ipoTarget,
				storage: "live",
				upperKey: "over-1p8t",
				assumptions: ipoAssumptions({
					discountRate: 0.1,
					expectedDate: "2027-12-31",
					lowerValue: 75_000,
					upperValue: 2_100_000,
					noIpoCurrentValue: 965_000,
					asOf: "2026-07-24T00:00:00.000Z",
					sourceUrl:
						"https://polymarket.com/event/anthropic-ipo-closing-market-cap-119",
				}),
				data: {
					provider: "polymarket",
					events: [
						{
							id: "lower",
							slug: "anthropic-ipo-closing-market-cap-119",
							url: "https://polymarket.com/event/anthropic-ipo-closing-market-cap-119",
							api: "https://gamma-api.polymarket.com/events/slug/anthropic-ipo-closing-market-cap-119",
						},
						{
							id: "upper",
							slug: "anthropic-ipo-closing-market-cap-979",
							url: "https://polymarket.com/event/anthropic-ipo-closing-market-cap-979",
							api: "https://gamma-api.polymarket.com/events/slug/anthropic-ipo-closing-market-cap-979",
						},
					],
					outcomes: [
						{
							event: "lower",
							sourceTitle: "<100B",
							key: "under-100b",
							label: "Below $100B",
							kind: "range",
							lower: null,
							upper: 100_000,
							representativeValue: 75_000,
							sortOrder: 1,
						},
						{
							event: "lower",
							sourceTitle: "100–200B",
							key: "100b-200b",
							label: "$100B–$200B",
							kind: "range",
							lower: 100_000,
							upper: 200_000,
							representativeValue: 150_000,
							sortOrder: 2,
						},
						{
							event: "lower",
							sourceTitle: "200–300B",
							key: "200b-300b",
							label: "$200B–$300B",
							kind: "range",
							lower: 200_000,
							upper: 300_000,
							representativeValue: 250_000,
							sortOrder: 3,
						},
						{
							event: "lower",
							sourceTitle: "300–400B",
							key: "300b-400b",
							label: "$300B–$400B",
							kind: "range",
							lower: 300_000,
							upper: 400_000,
							representativeValue: 350_000,
							sortOrder: 4,
						},
						{
							event: "lower",
							sourceTitle: "400–600B",
							key: "400b-600b",
							label: "$400B–$600B",
							kind: "range",
							lower: 400_000,
							upper: 600_000,
							representativeValue: 500_000,
							sortOrder: 5,
						},
						{
							event: "upper",
							sourceTitle: "0.6–0.9T",
							key: "600b-900b",
							label: "$600B–$900B",
							kind: "range",
							lower: 600_000,
							upper: 900_000,
							representativeValue: 750_000,
							sortOrder: 6,
						},
						{
							event: "upper",
							sourceTitle: "0.9–1.2T",
							key: "900b-1p2t",
							label: "$900B–$1.2T",
							kind: "range",
							lower: 900_000,
							upper: 1_200_000,
							representativeValue: 1_050_000,
							sortOrder: 7,
						},
						{
							event: "upper",
							sourceTitle: "1.2–1.5T",
							key: "1p2t-1p5t",
							label: "$1.2T–$1.5T",
							kind: "range",
							lower: 1_200_000,
							upper: 1_500_000,
							representativeValue: 1_350_000,
							sortOrder: 8,
						},
						{
							event: "upper",
							sourceTitle: "1.5–1.8T",
							key: "1p5t-1p8t",
							label: "$1.5T–$1.8T",
							kind: "range",
							lower: 1_500_000,
							upper: 1_800_000,
							representativeValue: 1_650_000,
							sortOrder: 9,
						},
						{
							event: "upper",
							sourceTitle: "1.8T+",
							key: "over-1p8t",
							label: "Above $1.8T",
							kind: "range",
							lower: 1_800_000,
							upper: null,
							representativeValue: 2_100_000,
							sortOrder: 10,
						},
						{
							event: "upper",
							sourceTitle: "No IPO by December 31, 2027",
							key: "no-ipo",
							label: "No IPO by deadline",
							kind: "no_ipo",
							lower: null,
							upper: null,
							representativeValue: null,
							sortOrder: 11,
						},
					],
				},
			},
			ipoMethod({
				id: "ipo-closing-higher-2027",
				weight: 0.5,
				event: "anthropic-ipo-closing-market-cap-higher-strikes",
				expectedDate: "2027-12-31",
				lowerValue: 1_000_000,
				upperValue: 3_500_000,
				noIpoCurrentValue: 965_000,
				asOf: "2026-07-30T00:00:00.000Z",
				upperKey: "over-3t",
				noIpoTitle: "No IPO by December 31, 2027",
				ranges: [
					{
						sourceTitle: "<$1.25T",
						key: "under-1p25t",
						label: "Below $1.25T",
						lower: null,
						upper: 1_250_000,
					},
					{
						sourceTitle: "$1.25–$1.5T",
						key: "1p25t-1p5t",
						label: "$1.25T–$1.5T",
						lower: 1_250_000,
						upper: 1_500_000,
					},
					{
						sourceTitle: "$1.5–$1.75T",
						key: "1p5t-1p75t",
						label: "$1.5T–$1.75T",
						lower: 1_500_000,
						upper: 1_750_000,
					},
					{
						sourceTitle: "$1.75–$2.0T",
						key: "1p75t-2t",
						label: "$1.75T–$2T",
						lower: 1_750_000,
						upper: 2_000_000,
					},
					{
						sourceTitle: "$2.0–$2.25T",
						key: "2t-2p25t",
						label: "$2T–$2.25T",
						lower: 2_000_000,
						upper: 2_250_000,
					},
					{
						sourceTitle: "$2.25–$2.5T",
						key: "2p25t-2p5t",
						label: "$2.25T–$2.5T",
						lower: 2_250_000,
						upper: 2_500_000,
					},
					{
						sourceTitle: "$2.5–$2.75T",
						key: "2p5t-2p75t",
						label: "$2.5T–$2.75T",
						lower: 2_500_000,
						upper: 2_750_000,
					},
					{
						sourceTitle: "$2.75–$3.0T",
						key: "2p75t-3t",
						label: "$2.75T–$3T",
						lower: 2_750_000,
						upper: 3_000_000,
					},
					{
						sourceTitle: "$3.0T+",
						key: "over-3t",
						label: "Above $3T",
						lower: 3_000_000,
						upper: null,
					},
				],
			}),
			{
				id: "valuation-high-2026",
				method: "prediction-market-valuation-thresholds",
				family: "prediction-market",
				familyWeight: 1,
				weight: 1,
				target: thresholdTarget,
				storage: "live",
				assumptions: thresholdAssumptions({
					growthRate: 0.1,
					expectedDate: "2026-12-31",
					floorValue: 965_000,
					upperValue: 5_500_000,
					asOf: "2026-07-28T00:00:00.000Z",
					sourceUrl:
						"https://polymarket.com/event/will-anthropics-valuation-hit-by-december-31",
				}),
				data: {
					provider: "polymarket",
					events: [
						{
							id: "main",
							slug: "will-anthropics-valuation-hit-by-december-31",
							url: "https://polymarket.com/event/will-anthropics-valuation-hit-by-december-31",
							api: "https://gamma-api.polymarket.com/events/slug/will-anthropics-valuation-hit-by-december-31",
						},
					],
					thresholds: [
						{
							event: "main",
							sourceTitle: "↑$1.0T",
							key: "over-1t",
							label: "$1T or higher",
							value: 1_000_000,
							sortOrder: 1,
						},
						{
							event: "main",
							sourceTitle: "↑$1.1T",
							key: "over-1p1t",
							label: "$1.1T or higher",
							value: 1_100_000,
							sortOrder: 2,
						},
						{
							event: "main",
							sourceTitle: "↑$1.25T",
							key: "over-1p25t",
							label: "$1.25T or higher",
							value: 1_250_000,
							sortOrder: 3,
						},
						{
							event: "main",
							sourceTitle: "↑$1.5T",
							key: "over-1p5t",
							label: "$1.5T or higher",
							value: 1_500_000,
							sortOrder: 4,
						},
						{
							event: "main",
							sourceTitle: "↑$1.75T",
							key: "over-1p75t",
							label: "$1.75T or higher",
							value: 1_750_000,
							sortOrder: 5,
						},
						{
							event: "main",
							sourceTitle: "↑$2.0T",
							key: "over-2t",
							label: "$2T or higher",
							value: 2_000_000,
							sortOrder: 6,
						},
						{
							event: "main",
							sourceTitle: "↑$2.5T",
							key: "over-2p5t",
							label: "$2.5T or higher",
							value: 2_500_000,
							sortOrder: 7,
						},
						{
							event: "main",
							sourceTitle: "↑$3.0T",
							key: "over-3t",
							label: "$3T or higher",
							value: 3_000_000,
							sortOrder: 8,
						},
						{
							event: "main",
							sourceTitle: "↑$4.0T",
							key: "over-4t",
							label: "$4T or higher",
							value: 4_000_000,
							sortOrder: 9,
						},
						{
							event: "main",
							sourceTitle: "↑$5.0T",
							key: "over-5t",
							label: "$5T or higher",
							value: 5_000_000,
							sortOrder: 10,
						},
					],
					claim: thresholdClaim("will-anthropics-valuation-hit-by-december-31"),
				},
			},
		],
	},
	{
		id: "openai",
		slug: "openai",
		name: "OpenAI",
		code: "OPENAI",
		number: "02",
		sector: "Artificial intelligence",
		description:
			"Polymarket provides two IPO-capitalization horizons for OpenAI plus a maximum qualifying valuation curve by deadline.",
		methods: [
			{
				id: "ipo-closing-2027",
				method: "prediction-market-ipo",
				family: "prediction-market",
				familyWeight: 1,
				weight: 0.5,
				target: ipoTarget,
				storage: "live",
				upperKey: "over-1p5t",
				assumptions: ipoAssumptions({
					discountRate: 0.1,
					expectedDate: "2027-12-31",
					lowerValue: 400_000,
					upperValue: 1_750_000,
					noIpoCurrentValue: 852_000,
					asOf: "2026-07-24T00:00:00.000Z",
					sourceUrl:
						"https://polymarket.com/event/openai-ipo-closing-market-cap-554",
				}),
				data: {
					provider: "polymarket",
					events: [
						{
							id: "main",
							slug: "openai-ipo-closing-market-cap-554",
							url: "https://polymarket.com/event/openai-ipo-closing-market-cap-554",
							api: "https://gamma-api.polymarket.com/events/slug/openai-ipo-closing-market-cap-554",
						},
					],
					outcomes: [
						{
							event: "main",
							sourceTitle: "<500B",
							key: "under-500b",
							label: "Below $500B",
							kind: "range",
							lower: null,
							upper: 500_000,
							representativeValue: 400_000,
							sortOrder: 1,
						},
						{
							event: "main",
							sourceTitle: "500–750B",
							key: "500b-750b",
							label: "$500B–$750B",
							kind: "range",
							lower: 500_000,
							upper: 750_000,
							representativeValue: 625_000,
							sortOrder: 2,
						},
						{
							event: "main",
							sourceTitle: "750B–1T",
							key: "750b-1t",
							label: "$750B–$1T",
							kind: "range",
							lower: 750_000,
							upper: 1_000_000,
							representativeValue: 875_000,
							sortOrder: 3,
						},
						{
							event: "main",
							sourceTitle: "1T–1.25T",
							key: "1t-1p25t",
							label: "$1T–$1.25T",
							kind: "range",
							lower: 1_000_000,
							upper: 1_250_000,
							representativeValue: 1_125_000,
							sortOrder: 4,
						},
						{
							event: "main",
							sourceTitle: "1.25T–1.5T",
							key: "1p25t-1p5t",
							label: "$1.25T–$1.5T",
							kind: "range",
							lower: 1_250_000,
							upper: 1_500_000,
							representativeValue: 1_375_000,
							sortOrder: 5,
						},
						{
							event: "main",
							sourceTitle: "1.5T+",
							key: "over-1p5t",
							label: "Above $1.5T",
							kind: "range",
							lower: 1_500_000,
							upper: null,
							representativeValue: 1_750_000,
							sortOrder: 6,
						},
						{
							event: "main",
							sourceTitle: "No IPO by December 31, 2027",
							key: "no-ipo",
							label: "No IPO by deadline",
							kind: "no_ipo",
							lower: null,
							upper: null,
							representativeValue: null,
							sortOrder: 7,
						},
					],
				},
			},
			ipoMethod({
				id: "ipo-closing-2026",
				weight: 0.5,
				event: "openai-ipo-closing-market-cap",
				expectedDate: "2026-12-31",
				lowerValue: 400_000,
				upperValue: 1_750_000,
				noIpoCurrentValue: 852_000,
				asOf: "2026-07-30T00:00:00.000Z",
				upperKey: "over-1p5t",
				noIpoTitle: "No IPO by December 31, 2026",
				ranges: [
					{
						sourceTitle: "<500B",
						key: "under-500b",
						label: "Below $500B",
						lower: null,
						upper: 500_000,
					},
					{
						sourceTitle: "500–750B",
						key: "500b-750b",
						label: "$500B–$750B",
						lower: 500_000,
						upper: 750_000,
					},
					{
						sourceTitle: "750B–1T",
						key: "750b-1t",
						label: "$750B–$1T",
						lower: 750_000,
						upper: 1_000_000,
					},
					{
						sourceTitle: "1T–1.25T",
						key: "1t-1p25t",
						label: "$1T–$1.25T",
						lower: 1_000_000,
						upper: 1_250_000,
					},
					{
						sourceTitle: "1.25T–1.5T",
						key: "1p25t-1p5t",
						label: "$1.25T–$1.5T",
						lower: 1_250_000,
						upper: 1_500_000,
					},
					{
						sourceTitle: "1.5T+",
						key: "over-1p5t",
						label: "Above $1.5T",
						lower: 1_500_000,
						upper: null,
					},
				],
			}),
			{
				id: "valuation-high-2026",
				method: "prediction-market-valuation-thresholds",
				family: "prediction-market",
				familyWeight: 1,
				weight: 1,
				target: thresholdTarget,
				storage: "live",
				assumptions: thresholdAssumptions({
					growthRate: 0.1,
					expectedDate: "2026-12-31",
					floorValue: 852_000,
					upperValue: 5_500_000,
					asOf: "2026-07-28T00:00:00.000Z",
					sourceUrl:
						"https://polymarket.com/event/will-openais-valuation-hit-by-december-31",
				}),
				data: {
					provider: "polymarket",
					events: [
						{
							id: "main",
							slug: "will-openais-valuation-hit-by-december-31",
							url: "https://polymarket.com/event/will-openais-valuation-hit-by-december-31",
							api: "https://gamma-api.polymarket.com/events/slug/will-openais-valuation-hit-by-december-31",
						},
					],
					thresholds: [
						{
							event: "main",
							sourceTitle: "↑$900B",
							key: "over-900b",
							label: "$900B or higher",
							value: 900_000,
							sortOrder: 1,
						},
						{
							event: "main",
							sourceTitle: "↑$1.0T",
							key: "over-1t",
							label: "$1T or higher",
							value: 1_000_000,
							sortOrder: 2,
						},
						{
							event: "main",
							sourceTitle: "↑$1.25T",
							key: "over-1p25t",
							label: "$1.25T or higher",
							value: 1_250_000,
							sortOrder: 3,
						},
						{
							event: "main",
							sourceTitle: "↑$1.5T",
							key: "over-1p5t",
							label: "$1.5T or higher",
							value: 1_500_000,
							sortOrder: 4,
						},
						{
							event: "main",
							sourceTitle: "↑$1.75T",
							key: "over-1p75t",
							label: "$1.75T or higher",
							value: 1_750_000,
							sortOrder: 5,
						},
						{
							event: "main",
							sourceTitle: "↑$2.0T",
							key: "over-2t",
							label: "$2T or higher",
							value: 2_000_000,
							sortOrder: 6,
						},
						{
							event: "main",
							sourceTitle: "↑$2.5T",
							key: "over-2p5t",
							label: "$2.5T or higher",
							value: 2_500_000,
							sortOrder: 7,
						},
						{
							event: "main",
							sourceTitle: "↑$3.0T",
							key: "over-3t",
							label: "$3T or higher",
							value: 3_000_000,
							sortOrder: 8,
						},
						{
							event: "main",
							sourceTitle: "↑$4.0T",
							key: "over-4t",
							label: "$4T or higher",
							value: 4_000_000,
							sortOrder: 9,
						},
						{
							event: "main",
							sourceTitle: "↑$5.0T",
							key: "over-5t",
							label: "$5T or higher",
							value: 5_000_000,
							sortOrder: 10,
						},
					],
					claim: thresholdClaim("will-openais-valuation-hit-by-december-31"),
				},
			},
		],
	},
	{
		id: "perplexity",
		slug: "perplexity",
		name: "Perplexity",
		code: "PERPLEXITY",
		number: "03",
		sector: "Artificial intelligence",
		description:
			"Polymarket provides two distinct Perplexity signals: an IPO-capitalization scenario and a maximum qualifying valuation by deadline.",
		methods: [
			{
				id: "ipo-closing-2027",
				method: "prediction-market-ipo",
				family: "prediction-market",
				familyWeight: 1,
				weight: 1,
				target: ipoTarget,
				storage: "live",
				upperKey: "over-100b",
				assumptions: ipoAssumptions({
					discountRate: 0.1,
					expectedDate: "2027-12-31",
					lowerValue: 15_000,
					upperValue: 125_000,
					noIpoCurrentValue: 20_000,
					asOf: "2026-07-24T00:00:00.000Z",
					sourceUrl:
						"https://polymarket.com/event/perplexity-ipo-closing-market-cap",
				}),
				data: {
					provider: "polymarket",
					events: [
						{
							id: "main",
							slug: "perplexity-ipo-closing-market-cap",
							url: "https://polymarket.com/event/perplexity-ipo-closing-market-cap",
							api: "https://gamma-api.polymarket.com/events/slug/perplexity-ipo-closing-market-cap",
						},
					],
					outcomes: [
						{
							event: "main",
							sourceTitle: "<20B",
							key: "under-20b",
							label: "Below $20B",
							kind: "range",
							lower: null,
							upper: 20_000,
							representativeValue: 15_000,
							sortOrder: 1,
						},
						{
							event: "main",
							sourceTitle: "20B–30B",
							key: "20b-30b",
							label: "$20B–$30B",
							kind: "range",
							lower: 20_000,
							upper: 30_000,
							representativeValue: 25_000,
							sortOrder: 2,
						},
						{
							event: "main",
							sourceTitle: "30B–40B",
							key: "30b-40b",
							label: "$30B–$40B",
							kind: "range",
							lower: 30_000,
							upper: 40_000,
							representativeValue: 35_000,
							sortOrder: 3,
						},
						{
							event: "main",
							sourceTitle: "40B–50B",
							key: "40b-50b",
							label: "$40B–$50B",
							kind: "range",
							lower: 40_000,
							upper: 50_000,
							representativeValue: 45_000,
							sortOrder: 4,
						},
						{
							event: "main",
							sourceTitle: "50B–75B",
							key: "50b-75b",
							label: "$50B–$75B",
							kind: "range",
							lower: 50_000,
							upper: 75_000,
							representativeValue: 62_500,
							sortOrder: 5,
						},
						{
							event: "main",
							sourceTitle: "75B–100B",
							key: "75b-100b",
							label: "$75B–$100B",
							kind: "range",
							lower: 75_000,
							upper: 100_000,
							representativeValue: 87_500,
							sortOrder: 6,
						},
						{
							event: "main",
							sourceTitle: "100B+",
							key: "over-100b",
							label: "Above $100B",
							kind: "range",
							lower: 100_000,
							upper: null,
							representativeValue: 125_000,
							sortOrder: 7,
						},
						{
							event: "main",
							sourceTitle: "No IPO before 2028",
							key: "no-ipo",
							label: "No IPO by deadline",
							kind: "no_ipo",
							lower: null,
							upper: null,
							representativeValue: null,
							sortOrder: 8,
						},
					],
				},
			},
			{
				id: "valuation-high-2026",
				method: "prediction-market-valuation-thresholds",
				family: "prediction-market",
				familyWeight: 1,
				weight: 1,
				target: thresholdTarget,
				storage: "live",
				assumptions: thresholdAssumptions({
					growthRate: 0.1,
					expectedDate: "2026-12-31",
					floorValue: 17_060,
					upperValue: 55_000,
					asOf: "2026-07-25T00:00:00.000Z",
					sourceUrl:
						"https://polymarket.com/event/will-perplexitys-valuation-hit-by-december-31",
				}),
				data: {
					provider: "polymarket",
					events: [
						{
							id: "main",
							slug: "will-perplexitys-valuation-hit-by-december-31",
							url: "https://polymarket.com/event/will-perplexitys-valuation-hit-by-december-31",
							api: "https://gamma-api.polymarket.com/events/slug/will-perplexitys-valuation-hit-by-december-31",
						},
					],
					thresholds: [
						{
							event: "main",
							sourceTitle: "↑$20B",
							key: "over-20b",
							label: "$20B or higher",
							value: 20_000,
							sortOrder: 1,
						},
						{
							event: "main",
							sourceTitle: "↑$22.5B",
							key: "over-22p5b",
							label: "$22.5B or higher",
							value: 22_500,
							sortOrder: 2,
						},
						{
							event: "main",
							sourceTitle: "↑$25B",
							key: "over-25b",
							label: "$25B or higher",
							value: 25_000,
							sortOrder: 3,
						},
						{
							event: "main",
							sourceTitle: "↑$30B",
							key: "over-30b",
							label: "$30B or higher",
							value: 30_000,
							sortOrder: 4,
						},
						{
							event: "main",
							sourceTitle: "↑$40B",
							key: "over-40b",
							label: "$40B or higher",
							value: 40_000,
							sortOrder: 5,
						},
						{
							event: "main",
							sourceTitle: "↑$50B",
							key: "over-50b",
							label: "$50B or higher",
							value: 50_000,
							sortOrder: 6,
						},
					],
					claim: thresholdClaim(
						"will-perplexitys-valuation-hit-by-december-31",
					),
				},
			},
		],
	},
	{
		id: "oura",
		slug: "oura",
		name: "Oura",
		code: "OURA",
		number: "04",
		sector: "Health technology",
		description:
			"A Polymarket IPO-cap ladder estimates Oura’s IPO-cap current equivalent from its 2026 outcome distribution.",
		methods: [
			{
				id: "ipo-closing-2026",
				method: "prediction-market-ipo",
				family: "prediction-market",
				familyWeight: 1,
				weight: 1,
				target: ipoTarget,
				storage: "live",
				upperKey: "over-20b",
				assumptions: ipoAssumptions({
					discountRate: 0.1,
					expectedDate: "2026-12-31",
					lowerValue: 5_000,
					upperValue: 22_500,
					noIpoCurrentValue: 11_000,
					asOf: "2026-07-25T00:00:00.000Z",
					sourceUrl: "https://polymarket.com/event/oura-ipo-closing-market-cap",
				}),
				data: {
					provider: "polymarket",
					events: [
						{
							id: "main",
							slug: "oura-ipo-closing-market-cap",
							url: "https://polymarket.com/event/oura-ipo-closing-market-cap",
							api: "https://gamma-api.polymarket.com/events/slug/oura-ipo-closing-market-cap",
						},
					],
					outcomes: [
						{
							event: "main",
							sourceTitle: "<$7.5B",
							key: "under-7p5b",
							label: "Below $7.5B",
							kind: "range",
							lower: null,
							upper: 7_500,
							representativeValue: 5_000,
							sortOrder: 1,
						},
						{
							event: "main",
							sourceTitle: "$7.5B–$10B",
							key: "7p5b-10b",
							label: "$7.5B–$10B",
							kind: "range",
							lower: 7_500,
							upper: 10_000,
							representativeValue: 8_750,
							sortOrder: 2,
						},
						{
							event: "main",
							sourceTitle: "$10B–$12.5B",
							key: "10b-12p5b",
							label: "$10B–$12.5B",
							kind: "range",
							lower: 10_000,
							upper: 12_500,
							representativeValue: 11_250,
							sortOrder: 3,
						},
						{
							event: "main",
							sourceTitle: "$12.5B–$15B",
							key: "12p5b-15b",
							label: "$12.5B–$15B",
							kind: "range",
							lower: 12_500,
							upper: 15_000,
							representativeValue: 13_750,
							sortOrder: 4,
						},
						{
							event: "main",
							sourceTitle: "$15B–$17.5B",
							key: "15b-17p5b",
							label: "$15B–$17.5B",
							kind: "range",
							lower: 15_000,
							upper: 17_500,
							representativeValue: 16_250,
							sortOrder: 5,
						},
						{
							event: "main",
							sourceTitle: "$17.5B–$20B",
							key: "17p5b-20b",
							label: "$17.5B–$20B",
							kind: "range",
							lower: 17_500,
							upper: 20_000,
							representativeValue: 18_750,
							sortOrder: 6,
						},
						{
							event: "main",
							sourceTitle: "$20B+",
							key: "over-20b",
							label: "Above $20B",
							kind: "range",
							lower: 20_000,
							upper: null,
							representativeValue: 22_500,
							sortOrder: 7,
						},
						{
							event: "main",
							sourceTitle: "No IPO before January 2027",
							key: "no-ipo",
							label: "No IPO by deadline",
							kind: "no_ipo",
							lower: null,
							upper: null,
							representativeValue: null,
							sortOrder: 8,
						},
					],
				},
			},
		],
	},
	{
		id: "strava",
		slug: "strava",
		name: "Strava",
		code: "STRAVA",
		number: "05",
		sector: "Fitness technology",
		description:
			"Strava’s IPO-cap current equivalent derived from a nine-outcome 2027 Polymarket ladder.",
		methods: [
			{
				id: "ipo-closing-2027",
				method: "prediction-market-ipo",
				family: "prediction-market",
				familyWeight: 1,
				weight: 1,
				target: ipoTarget,
				storage: "live",
				upperKey: "over-15b",
				assumptions: ipoAssumptions({
					discountRate: 0.1,
					expectedDate: "2027-12-31",
					lowerValue: 1_500,
					upperValue: 17_500,
					noIpoCurrentValue: 2_200,
					asOf: "2026-07-25T00:00:00.000Z",
					sourceUrl:
						"https://polymarket.com/event/strava-ipo-closing-market-cap",
				}),
				data: {
					provider: "polymarket",
					events: [
						{
							id: "main",
							slug: "strava-ipo-closing-market-cap",
							url: "https://polymarket.com/event/strava-ipo-closing-market-cap",
							api: "https://gamma-api.polymarket.com/events/slug/strava-ipo-closing-market-cap",
						},
					],
					outcomes: [
						{
							event: "main",
							sourceTitle: "<2B",
							key: "under-2b",
							label: "Below $2B",
							kind: "range",
							lower: null,
							upper: 2_000,
							representativeValue: 1_500,
							sortOrder: 1,
						},
						{
							event: "main",
							sourceTitle: "2B–3B",
							key: "2b-3b",
							label: "$2B–$3B",
							kind: "range",
							lower: 2_000,
							upper: 3_000,
							representativeValue: 2_500,
							sortOrder: 2,
						},
						{
							event: "main",
							sourceTitle: "3B–4B",
							key: "3b-4b",
							label: "$3B–$4B",
							kind: "range",
							lower: 3_000,
							upper: 4_000,
							representativeValue: 3_500,
							sortOrder: 3,
						},
						{
							event: "main",
							sourceTitle: "4B–5B",
							key: "4b-5b",
							label: "$4B–$5B",
							kind: "range",
							lower: 4_000,
							upper: 5_000,
							representativeValue: 4_500,
							sortOrder: 4,
						},
						{
							event: "main",
							sourceTitle: "5B–7B",
							key: "5b-7b",
							label: "$5B–$7B",
							kind: "range",
							lower: 5_000,
							upper: 7_000,
							representativeValue: 6_000,
							sortOrder: 5,
						},
						{
							event: "main",
							sourceTitle: "7B–10B",
							key: "7b-10b",
							label: "$7B–$10B",
							kind: "range",
							lower: 7_000,
							upper: 10_000,
							representativeValue: 8_500,
							sortOrder: 6,
						},
						{
							event: "main",
							sourceTitle: "10B–15B",
							key: "10b-15b",
							label: "$10B–$15B",
							kind: "range",
							lower: 10_000,
							upper: 15_000,
							representativeValue: 12_500,
							sortOrder: 7,
						},
						{
							event: "main",
							sourceTitle: "15B+",
							key: "over-15b",
							label: "Above $15B",
							kind: "range",
							lower: 15_000,
							upper: null,
							representativeValue: 17_500,
							sortOrder: 8,
						},
						{
							event: "main",
							sourceTitle: "No IPO before 2028",
							key: "no-ipo",
							label: "No IPO by deadline",
							kind: "no_ipo",
							lower: null,
							upper: null,
							representativeValue: null,
							sortOrder: 9,
						},
					],
				},
			},
		],
	},
	{
		id: "discord",
		slug: "discord",
		name: "Discord",
		code: "DISCORD",
		number: "06",
		sector: "Consumer technology",
		description:
			"A Polymarket IPO-cap ladder estimates Discord’s IPO-cap current equivalent from its 2027 outcome distribution.",
		methods: [
			{
				id: "ipo-closing-2027",
				method: "prediction-market-ipo",
				family: "prediction-market",
				familyWeight: 1,
				weight: 1,
				target: ipoTarget,
				storage: "live",
				upperKey: "over-20b",
				assumptions: ipoAssumptions({
					discountRate: 0.1,
					expectedDate: "2027-12-31",
					lowerValue: 3_500,
					upperValue: 23_000,
					noIpoCurrentValue: 15_000,
					asOf: "2026-07-25T00:00:00.000Z",
					sourceUrl:
						"https://polymarket.com/event/discord-ipo-closing-market-cap-20260626185933220",
				}),
				data: {
					provider: "polymarket",
					events: [
						{
							id: "main",
							slug: "discord-ipo-closing-market-cap-20260626185933220",
							url: "https://polymarket.com/event/discord-ipo-closing-market-cap-20260626185933220",
							api: "https://gamma-api.polymarket.com/events/slug/discord-ipo-closing-market-cap-20260626185933220",
						},
					],
					outcomes: [
						{
							event: "main",
							sourceTitle: "<5B",
							key: "under-5b",
							label: "Below $5B",
							kind: "range",
							lower: null,
							upper: 5_000,
							representativeValue: 3_500,
							sortOrder: 1,
						},
						{
							event: "main",
							sourceTitle: "5–8B",
							key: "5b-8b",
							label: "$5B–$8B",
							kind: "range",
							lower: 5_000,
							upper: 8_000,
							representativeValue: 6_500,
							sortOrder: 2,
						},
						{
							event: "main",
							sourceTitle: "8–11B",
							key: "8b-11b",
							label: "$8B–$11B",
							kind: "range",
							lower: 8_000,
							upper: 11_000,
							representativeValue: 9_500,
							sortOrder: 3,
						},
						{
							event: "main",
							sourceTitle: "11–14B",
							key: "11b-14b",
							label: "$11B–$14B",
							kind: "range",
							lower: 11_000,
							upper: 14_000,
							representativeValue: 12_500,
							sortOrder: 4,
						},
						{
							event: "main",
							sourceTitle: "14–17B",
							key: "14b-17b",
							label: "$14B–$17B",
							kind: "range",
							lower: 14_000,
							upper: 17_000,
							representativeValue: 15_500,
							sortOrder: 5,
						},
						{
							event: "main",
							sourceTitle: "17–20B",
							key: "17b-20b",
							label: "$17B–$20B",
							kind: "range",
							lower: 17_000,
							upper: 20_000,
							representativeValue: 18_500,
							sortOrder: 6,
						},
						{
							event: "main",
							sourceTitle: "20B+",
							key: "over-20b",
							label: "Above $20B",
							kind: "range",
							lower: 20_000,
							upper: null,
							representativeValue: 23_000,
							sortOrder: 7,
						},
						{
							event: "main",
							sourceTitle: "No IPO by December 31, 2027",
							key: "no-ipo",
							label: "No IPO by deadline",
							kind: "no_ipo",
							lower: null,
							upper: null,
							representativeValue: null,
							sortOrder: 8,
						},
					],
				},
			},
		],
	},
	thresholdCompany({
		id: "bytedance",
		name: "ByteDance",
		code: "BYTEDANCE",
		number: "07",
		sector: "Consumer internet",
		event: "will-bytedances-valuation-hit-by-december-31-20260701011753589",
		floorValue: 550_000,
		upperValue: 2_000_000,
		thresholds: [
			["↑$650B", 650_000],
			["↑$700B", 700_000],
			["↑$800B", 800_000],
			["↑$900B", 900_000],
			["↑$1.0T", 1_000_000],
			["↑$1.25T", 1_250_000],
			["↑$1.5T", 1_500_000],
		],
	}),
	thresholdCompany({
		id: "stripe",
		name: "Stripe",
		code: "STRIPE",
		number: "08",
		sector: "Financial technology",
		event: "will-stripes-valuation-hit-by-december-31",
		floorValue: 170_000,
		upperValue: 600_000,
		thresholds: [
			["↑$190B", 190_000],
			["↑$200B", 200_000],
			["↑$225B", 225_000],
			["↑$250B", 250_000],
			["↑$300B", 300_000],
			["↑$400B", 400_000],
			["↑$500B", 500_000],
		],
	}),
	thresholdCompany({
		id: "anduril",
		name: "Anduril",
		code: "ANDURIL",
		number: "09",
		sector: "Defense technology",
		event: "will-andurils-valuation-hit-by-december-31",
		floorValue: 100_000,
		upperValue: 250_000,
		thresholds: [
			["↑$110B", 110_000],
			["↑$125B", 125_000],
			["↑$150B", 150_000],
			["↑$175B", 175_000],
			["↑$200B", 200_000],
		],
	}),
	thresholdCompany({
		id: "kraken",
		name: "Kraken",
		code: "KRAKEN",
		number: "10",
		sector: "Cryptocurrency",
		event: "will-krakens-valuation-hit-by-december-31",
		floorValue: 10_000,
		upperValue: 30_000,
		thresholds: [
			["↑$12.5B", 12_500],
			["↑$15B", 15_000],
			["↑$17.5B", 17_500],
			["↑$20B", 20_000],
			["↑$22.5B", 22_500],
			["↑$25B", 25_000],
		],
	}),
	thresholdCompany({
		id: "databricks",
		name: "Databricks",
		code: "DATABRICKS",
		number: "11",
		sector: "Data and artificial intelligence",
		event: "will-databricks-valuation-hit-by-december-31",
		floorValue: 170_000,
		upperValue: 350_000,
		thresholds: [
			["↑$180B", 180_000],
			["↑$190B", 190_000],
			["↑$200B", 200_000],
			["↑$225B", 225_000],
			["↑$250B", 250_000],
			["↑$300B", 300_000],
		],
	}),
	thresholdCompany({
		id: "epic-games",
		name: "Epic Games",
		code: "EPIC GAMES",
		number: "12",
		sector: "Interactive entertainment",
		event: "will-epic-games-valuation-hit-by-december-31",
		floorValue: 12_500,
		upperValue: 35_000,
		thresholds: [
			["↑$13.5B", 13_500],
			["↑$14B", 14_000],
			["↑$15B", 15_000],
			["↑$17.5B", 17_500],
			["↑$20B", 20_000],
			["↑$25B", 25_000],
			["↑$30B", 30_000],
		],
	}),
	thresholdCompany({
		id: "neuralink",
		name: "Neuralink",
		code: "NEURALINK",
		number: "13",
		sector: "Neurotechnology",
		event: "will-neuralinks-valuation-hit-by-december-31",
		floorValue: 45_000,
		upperValue: 125_000,
		thresholds: [
			["↑$50B", 50_000],
			["↑$60B", 60_000],
			["↑$75B", 75_000],
			["↑$100B", 100_000],
		],
	}),
	thresholdCompany({
		id: "canva",
		name: "Canva",
		code: "CANVA",
		number: "14",
		sector: "Design software",
		event: "will-canvas-valuation-hit-by-december-31",
		floorValue: 40_000,
		upperValue: 125_000,
		thresholds: [
			["↑$45B", 45_000],
			["↑$50B", 50_000],
			["↑$60B", 60_000],
			["↑$75B", 75_000],
			["↑$100B", 100_000],
		],
	}),
];
